language: shell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran
  - ./download-cutest.sh
install: ./install-cutest.sh
script:
  - ./test-cutest.sh
  - cd c-code; ./test-main.sh
  - cd julia-code; ./test-main.sh
notifications:
  email:
    on_success: always
